### ISSUE TITLE
xmlRoundtripTest failed

### ISSUE THREAD

**Issue by milos-cuculovic** [znerol/node-delta#11]
Hello, I have an issue while running the make test:

> xmlRoundtripTest
✖ SVG roundtrip (XCC)

> Error: Failed to start attribute
    at Object.TextWriter.startAttributeNS (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/libxmljs/lib/textwriter.js:110:15)
    at DOMWriter.writeAttribute (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:73:17)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:55:18)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeDocument (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:95:10)

> ✔ SVG identity (XCC)
✖ SVG roundtrip (Skel-Match)

> Error: Failed to start attribute
 Object.TextWriter.startAttributeNS (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/libxmljs/lib/textwriter.js:110:15)
    at DOMWriter.writeAttribute (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:73:17)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:55:18)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeNode (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:8:18)
    at DOMWriter.writeElement (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:60:14)
    at DOMWriter.writeDocument (/Users/miloscuculovic/PycharmProjects/XMLDiffAnalyzer/XMLDiffTools/node-delta/node_modules/xmlshim/domwriter.js:95:10)

Am I missing something? Thank you in advance.

**Comment by znerol** [comment]
Thanks for the report. Could you please specify which node version and OS you are using.

**Comment by milos-cuculovic** [comment]
Thanks znerol! v12.16.1 on OSx

**Comment by znerol** [comment]
Oh, interesting. The [last travis job](https://travis-ci.org/znerol/node-delta/jobs/633628752) shows the same failures on Linux for all node versions :/

**Comment by milos-cuculovic** [comment]
That's exactly the one I have.
Confirming node 10 works well with the 0.0.5 release of node-delta, but would be good to also use the upgraded version and enjoy new & improved features :)

**Comment by znerol** [comment]
Looks like this was caused by an update to `xmlshim` dependencies. If I downgrade `jsdom` over there, then the tests [pass](https://travis-ci.org/znerol/node-delta/builds/657910540)

**Comment by znerol** [comment]
Published 0.0.7, that one should work now with node 12

**Comment by milos-cuculovic** [comment]
Thanks a lot, works now.
